### ISSUE TITLE
IndexError: string not matched

### ISSUE THREAD

**Issue by mykhi** [itay-grudev/es-tutorial#2]
Whenever you try to search for a string with uppercases it fails with 
`IndexError: string not matched` error as it tries to match uppercases string to unexisting symbol.

To fix this you could add `downcase` in ./app/helpers/search_helper.rb:30

from:
`new_query = query.dup`
to:
`new_query = query.downcase.dup`

**Comment by itay-grudev** [comment]
This isn't the case for me.

**Comment by mykhi** [comment]
Please try searching for "Rails framwOrk"

**Comment by mattbilbow** [comment]
@mykhi - This is not the case for me either. I cannot reproduce this error.

Thanks for the great tutorial, @itay-grudev 

![screen shot 2017-10-16 at 15 45 13](https://user-images.githubusercontent.com/1419220/31618148-0a669548-b289-11e7-8ee2-2320d4a9f3c3.png)

**Comment by mykhi** [comment]
I found out later on it was related to newer version of ruby or rails (I probably used 5). AFAIR downgrading one or another made it ignore the capitals and work as per tutorial.
